# Autostart necessary processes and desired applications upon login
exec-once = hyprpaper & waybar
exec-once = systemctl --user start hyprpolkitagent

# Uncomment once script is working
# exec-once = ~/.config/hypr/scripts/startup-apps.sh
